[book]
authors = ['inauris']
language = 'ru'
multilingual = false
src = 'src'
title = 'База знаний: Песков Сергей'

[build]
build-dir = 'public'

[preprocessor.toc]
command = './mdbook-toc'
renderer = ['html']
